### ISSUE TITLE
Errors building the MSP external. Compiled version available?

### ISSUE THREAD

**Issue by th-hu** [jamiebullock/LibXtract#49]
Hallo, 
xtract seems quite interesting. I like the lightweight do one thing and do it well design. Can't wait to try it out, but I struggle compiling the xtract~ external. 

I'm on OSX 10.9. xtract worked, but "cd examples/MSP/ && make" not.
Probably just wrong dependencies or parameters. Which OSX SDK and Max SDK did you use?
Or can I get a compiled Version somewhere?

**Comment by jamiebullock** [comment]
The Max and Pd externals have been removed, and will be replaced by a single fleet-based code base. See #81
