### ISSUE TITLE
 xtract_power

### ISSUE THREAD

**Issue by q-depot** [jamiebullock/LibXtract#71]
I'm extracting the power of the spectrum and it's always 0 no matter how much gain I apply.

**Comment by jamiebullock** [comment]
That's because `xtract_power()` isn't implemented!

You should check the return codes from feature extraction functions for `XTRACT_SUCCESS`. One of the error codes is `XTRACT_FEATURE_NOT_IMPLEMENTED`, which indeed `xtract_power()` returns :)
