### ISSUE TITLE
Building Pure Data external

### ISSUE THREAD

**Issue by ronttis** [jamiebullock/LibXtract#74]
Hello,

I need to perform audio feature analysis in Pure Data and I found out that LibXtract could be superb for the task.

Unfortunately, I am facing problems trying to build the PD external on OS X. "make install" does not produce any error messages and it creates folder containing three sub-folders (bin, include and lib). I can not find anything related to Pure Data inside these folders (nor in any other folders). I guess I am doing something horribly wrong.

I would be extremely grateful, if you could provide instructions on how to build the PD external.

Best regards,
Thomas

**Comment by jamiebullock** [comment]
Hi, I removed the Pure Data external because I have limited time to maintain LibXtract and I found people were having issues with the externals for Max and Pd.There will at some point be a new Pd external based on flext, see: #81
