### ISSUE TITLE
Python bindings not installed with build

### ISSUE THREAD

**Issue by PGryllos** [jamiebullock/LibXtract#75]
This may be my mistake but I cannot figure out how to install the python bindings.
I downloaded the latest version of the project through github. In the official documentation the only thing mentioned is that you need SWIG and python. In older documentations it is stated that you need to run `./configure` with specific arguments in order to install the python bindings.

I have python 3.4.3 and SWIG is installed but I cannot find a configure file. When I run `make` the swig folder is not entered. If I manually enter the folder and run `make` I get the following results

../include/xtract/libxtract.h:300: Warning 314: 'def' is a python keyword, renaming to '_def'
cc: error: Accelerate: No such file or directory
cc: error: unrecognized command line option ‘-framework’
Makefile:21: recipe for target 'python' failed
make: *** [python] Error 1
 
Also in the swig folder if I run the test.py I get the "Failed to load the library "xtract"" error.

**Comment by sebpiq** [comment]
Same here ... output from `make install` is just : 

```
make[1]: Entering directory `/root/LibXtract/src'
make[1]: Leaving directory `/root/LibXtract/src'
make[1]: Entering directory `/root/LibXtract/examples'
make[2]: Entering directory `/root/LibXtract/examples/simpletest'
WaveFile.cpp:75:8: warning: multi-character character constant [-Wmultichar]
   case 'FFIR':
        ^
WaveFile.cpp:81:31: warning: multi-character character constant [-Wmultichar]
     if (header.riff.format != 'EVAW')
                               ^
WaveFile.cpp:89:8: warning: multi-character character constant [-Wmultichar]
   case ' tmf':
        ^
WaveFile.cpp:124:8: warning: multi-character character constant [-Wmultichar]
   case 'atad':
        ^
WaveFile.cpp:143:29: warning: multi-character character constant [-Wmultichar]
  if (header.riff.chunkID != 'FFIR')
                             ^
WaveFile.cpp:148:28: warning: multi-character character constant [-Wmultichar]
  if (header.fmt.chunkID != ' tmf')
                            ^
make[2]: Leaving directory `/root/LibXtract/examples/simpletest'
make[1]: Leaving directory `/root/LibXtract/examples'
```

@jamiebullock did you remove the Python bindings?

**Comment by jamiebullock** [comment]
Hi, no the python bindings haven't been removed, you just now need to build them as a separate step with `make swig`. I'll add this detail to the README!

**Comment by sebpiq** [comment]
Great, thanks for the info :)
I actually ended up using an old version of libxtract that I knew to compile properly ...

**Comment by hannahwolfe** [comment]
Which version did you use?
