### ISSUE TITLE
fabs warnings

### ISSUE THREAD

**Issue by shdevin** [jamiebullock/LibXtract#78]
May I ask why the three fabs warnings have been left untouched?

Thanks,
 Dev

**Comment by jamiebullock** [comment]
The reason is "historical". Either dywapitchtrack was included as a submodule and I didn't know how to push changes upstream, or the warning simply wasn't showing with the old build system flags.

Anyhow, it's fixed now with a PR here: https://github.com/antoineschmitt/dywapitchtrack/pull/1
